export const ENV_VARIABLES = {
  GOOGLE_CLIENT_ID: `${import.meta.env.VITE_GOOGLE_CLIENT_ID}`,
  NOTION_API_KEY: `${import.meta.env.VITE_NOTION_INTERNAL_INTEGRATION_SECRET}`,
  NOTION_PAGE_ID: `${import.meta.env.VITE_NOTION_PAGE_ID}`
}
